// src/config/modulosConfig.js
// 🎯 FUENTE ÚNICA DE VERDAD - Configuración centralizada de módulos
// Todos los dashboards leen de aquí para evitar duplicación

/**
 * CONFIGURACIÓN POR UNIDADES DE NEGOCIO
 * Usada por: DashboardUnidad.jsx, DashboardUnidades.jsx
 */
export const modulosPorUnidad = {
  1: {
    nombre: "PESCA INDUSTRIAL",
    icono: "🚢",
    color: "#1E40AF",
    descripcion: "Temporadas, faenas, descargas y cuotas de pesca industrial",
    procesosPrincipales: [
      {
        id: "temporadaPesca",
        titulo: "Temporadas de Pesca",
        descripcion: "Gestión de temporadas y cuotas",
        icono: "pi-calendar",
        color: "#1E40AF",
        tablas: [
          { id: "detCuotaPesca", titulo: "Detalle Cuotas Pesca", icono: "pi-percentage" },
          { id: "accionesPreviasFaena", titulo: "Acciones Previas Faena", icono: "pi-list" },
          { id: "embarcacion", titulo: "Embarcaciones", icono: "pi-compass" },
          { id: "tipoEmbarcacion", titulo: "Tipo Embarcación", icono: "pi-tag" },
          { id: "bolicheRed", titulo: "Boliche de Red", icono: "pi-circle" },
          { id: "documentoPesca", titulo: "Documentación Pesca", icono: "pi-file" },
          { id: "documentacionEmbarcacion", titulo: "Documentación Embarcación", icono: "pi-file-edit" },
          { id: "documentacionPersonal", titulo: "Documentación Personal", icono: "pi-id-card" },
          { id: "especie", titulo: "Especies", icono: "pi-star" },
          { id: "katanaTripulacion", titulo: "Katana Tripulación", icono: "pi-users" },
          { id: "puertoPesca", titulo: "Puerto de Pesca", icono: "pi-map-marker" },
        ],
      },
      {
        id: "oTMantenimiento",
        titulo: "Órdenes de Trabajo",
        descripcion: "Mantenimiento",
        icono: "pi-wrench",
        color: "#DC2626",
        tablas: [
          { id: "activo", titulo: "Activos", icono: "pi-cog" },
          { id: "tipoActivo", titulo: "Tipos de Activo", icono: "pi-tag" },
          { id: "tipoMantenimiento", titulo: "Tipos de Mantenimiento", icono: "pi-wrench" },
        ],
      },
      {
        id: "requerimientoCompra",
        titulo: "Requerimientos de Compra",
        descripcion: "Solicitudes de compra",
        icono: "pi-file-edit",
        color: "#1E8449",
        tablas: [
          { id: "tipoProducto", titulo: "Tipo Producto", icono: "pi-tag" },
          { id: "tipoEstadoProducto", titulo: "Tipo Estado Producto", icono: "pi-circle" },
          { id: "destinoProducto", titulo: "Destino Producto", icono: "pi-map-marker" },
          { id: "formaPago", titulo: "Forma de Pago", icono: "pi-credit-card" },
          { id: "modoDespachoRecepcion", titulo: "Modo Despacho/Recepción", icono: "pi-truck" },
        ],
      },
      {
        id: "ordenCompra",
        titulo: "Órdenes de Compra",
        descripcion: "Órdenes aprobadas",
        icono: "pi-shopping-cart",
        color: "#1E8449",
        tablas: [
          { id: "producto", titulo: "Producto", icono: "pi-box" },
          { id: "entidadComercial", titulo: "Entidades Comerciales", icono: "pi-building" },
        ],
      },
      {
        id: "movimientoAlmacen",
        titulo: "Movimientos de Almacén",
        descripcion: "Control de inventarios",
        icono: "pi-box",
        color: "#2874A6",
        tablas: [
          { id: "conceptoMovAlmacen", titulo: "Conceptos Movimientos", icono: "pi-tags" },
          { id: "tipoDocumento", titulo: "Tipos de Documento", icono: "pi-file" },
          { id: "tipoConcepto", titulo: "Tipos de Concepto", icono: "pi-tag" },
          { id: "tipoMovimientoAlmacen", titulo: "Tipos de Movimiento", icono: "pi-arrows-h" },
          { id: "tipoAlmacen", titulo: "Tipos de Almacén", icono: "pi-building" },
          { id: "centrosAlmacen", titulo: "Centros de Almacén", icono: "pi-sitemap" },
          { id: "almacen", titulo: "Almacenes", icono: "pi-warehouse" },
          { id: "serieDoc", titulo: "Series de Documento", icono: "pi-hashtag" },
        ],
      },
      {
        id: "preFactura",
        titulo: "Pre-Facturas",
        descripcion: "Pre-facturas de exportación",
        icono: "pi-file",
        color: "#5DADE2",
        tablas: [
          { id: "incoterm", titulo: "Incoterms", icono: "pi-globe" },
          { id: "docRequeridaVentas", titulo: "Documentos Requeridos Ventas", icono: "pi-file-check" },
          { id: "requisitoDocPorPais", titulo: "Requisitos Doc. por País", icono: "pi-flag" },
          { id: "tipoContenedor", titulo: "Tipo Contenedor", icono: "pi-box" },
          { id: "formaTransaccion", titulo: "Formas Transacción", icono: "pi-credit-card" },
        ],
      },
    ],
  },
  2: {
    nombre: "PESCA CONSUMO",
    icono: "🐟",
    color: "#059669",
    descripcion: "Novedades, faenas y descargas de pesca de consumo humano",
    procesosPrincipales: [
      {
        id: "novedadPescaConsumo",
        titulo: "Novedades Pesca Consumo",
        descripcion: "Registro de novedades",
        icono: "pi-file-edit",
        color: "#059669",
        tablas: [
          { id: "embarcacion", titulo: "Embarcaciones", icono: "pi-compass" },
          { id: "tipoEmbarcacion", titulo: "Tipo Embarcación", icono: "pi-tag" },
          { id: "documentoPesca", titulo: "Documentación Pesca", icono: "pi-file" },
          { id: "documentacionEmbarcacion", titulo: "Documentación Embarcación", icono: "pi-file-edit" },
          { id: "documentacionPersonal", titulo: "Documentación Personal", icono: "pi-id-card" },
          { id: "especie", titulo: "Especies", icono: "pi-star" },
          { id: "katanaTripulacion", titulo: "Katana Tripulación", icono: "pi-users" },
          { id: "puertoPesca", titulo: "Puerto de Pesca", icono: "pi-map-marker" },
        ],
      },
      {
        id: "oTMantenimiento",
        titulo: "Órdenes de Trabajo",
        descripcion: "Mantenimiento",
        icono: "pi-wrench",
        color: "#DC2626",
        tablas: [
          { id: "activo", titulo: "Activos", icono: "pi-cog" },
          { id: "tipoActivo", titulo: "Tipos de Activo", icono: "pi-tag" },
          { id: "tipoMantenimiento", titulo: "Tipos de Mantenimiento", icono: "pi-wrench" },
        ],
      },
      {
        id: "requerimientoCompra",
        titulo: "Requerimientos de Compra",
        descripcion: "Solicitudes de compra",
        icono: "pi-file-edit",
        color: "#1E8449",
        tablas: [
          { id: "tipoProducto", titulo: "Tipo Producto", icono: "pi-tag" },
          { id: "tipoEstadoProducto", titulo: "Tipo Estado Producto", icono: "pi-circle" },
          { id: "destinoProducto", titulo: "Destino Producto", icono: "pi-map-marker" },
          { id: "formaPago", titulo: "Forma de Pago", icono: "pi-credit-card" },
          { id: "modoDespachoRecepcion", titulo: "Modo Despacho/Recepción", icono: "pi-truck" },
        ],
      },
      {
        id: "ordenCompra",
        titulo: "Órdenes de Compra",
        descripcion: "Órdenes aprobadas",
        icono: "pi-shopping-cart",
        color: "#1E8449",
        tablas: [
          { id: "producto", titulo: "Producto", icono: "pi-box" },
          { id: "entidadComercial", titulo: "Entidades Comerciales", icono: "pi-building" },
        ],
      },
      {
        id: "movimientoAlmacen",
        titulo: "Movimientos de Almacén",
        descripcion: "Control de inventarios",
        icono: "pi-box",
        color: "#2874A6",
        tablas: [
          { id: "conceptoMovAlmacen", titulo: "Conceptos Movimientos", icono: "pi-tags" },
          { id: "tipoDocumento", titulo: "Tipos de Documento", icono: "pi-file" },
          { id: "tipoConcepto", titulo: "Tipos de Concepto", icono: "pi-tag" },
          { id: "tipoMovimientoAlmacen", titulo: "Tipos de Movimiento", icono: "pi-arrows-h" },
          { id: "tipoAlmacen", titulo: "Tipos de Almacén", icono: "pi-building" },
          { id: "centrosAlmacen", titulo: "Centros de Almacén", icono: "pi-sitemap" },
          { id: "almacen", titulo: "Almacenes", icono: "pi-warehouse" },
          { id: "serieDoc", titulo: "Series de Documento", icono: "pi-hashtag" },
        ],
      },
      {
        id: "preFactura",
        titulo: "Pre-Facturas",
        descripcion: "Pre-facturas de exportación",
        icono: "pi-file",
        color: "#5DADE2",
        tablas: [
          { id: "moneda", titulo: "Monedas", icono: "pi-money-bill" },
          { id: "tipoEntidad", titulo: "Tipos Entidad", icono: "pi-briefcase" },
          { id: "agrupacionEntidad", titulo: "Agrupaciones Entidad", icono: "pi-sitemap" },
          { id: "unidadMedida", titulo: "Unidad Medida", icono: "pi-chart-bar" },
          { id: "personal", titulo: "Personal", icono: "pi-users" },
          { id: "cargoPersonal", titulo: "Cargos Personal", icono: "pi-id-card" },
          { id: "pais", titulo: "País", icono: "pi-flag" },
          { id: "familiaProducto", titulo: "Familia Producto", icono: "pi-th-large" },
          { id: "subfamiliaProducto", titulo: "Subfamilia Producto", icono: "pi-list" },
        ],
      },
    ],
  },
  3: {
    nombre: "CONSERVAS DE PESCADO",
    icono: "🥫",
    color: "#DC2626",
    descripcion: "Producción y comercialización de conservas hidrobiológicas",
    procesosPrincipales: [
      {
        id: "requerimientoCompra",
        titulo: "Requerimientos de Compra",
        descripcion: "Solicitudes de compra",
        icono: "pi-file-edit",
        color: "#1E8449",
        tablas: [
          { id: "producto", titulo: "Producto", icono: "pi-box" },
          { id: "entidadComercial", titulo: "Entidades Comerciales", icono: "pi-building" },
        ],
      },
      {
        id: "ordenCompra",
        titulo: "Órdenes de Compra",
        descripcion: "Órdenes aprobadas",
        icono: "pi-shopping-cart",
        color: "#1E8449",
        tablas: [
          { id: "tipoProducto", titulo: "Tipo Producto", icono: "pi-tag" },
          { id: "tipoEstadoProducto", titulo: "Tipo Estado Producto", icono: "pi-circle" },
          { id: "destinoProducto", titulo: "Destino Producto", icono: "pi-map-marker" },
          { id: "formaPago", titulo: "Forma de Pago", icono: "pi-credit-card" },
          { id: "modoDespachoRecepcion", titulo: "Modo Despacho/Recepción", icono: "pi-truck" },
        ],
      },
      {
        id: "movimientoAlmacen",
        titulo: "Movimientos de Almacén",
        descripcion: "Control de inventarios",
        icono: "pi-box",
        color: "#2874A6",
        tablas: [
          { id: "conceptoMovAlmacen", titulo: "Conceptos Movimientos", icono: "pi-tags" },
          { id: "tipoDocumento", titulo: "Tipos de Documento", icono: "pi-file" },
          { id: "tipoConcepto", titulo: "Tipos de Concepto", icono: "pi-tag" },
          { id: "tipoMovimientoAlmacen", titulo: "Tipos de Movimiento", icono: "pi-arrows-h" },
          { id: "tipoAlmacen", titulo: "Tipos de Almacén", icono: "pi-building" },
          { id: "centrosAlmacen", titulo: "Centros de Almacén", icono: "pi-sitemap" },
          { id: "almacen", titulo: "Almacenes", icono: "pi-warehouse" },
          { id: "serieDoc", titulo: "Series de Documento", icono: "pi-hashtag" },
        ],
      },
      {
        id: "cotizacionVentas",
        titulo: "Cotización Ventas",
        descripcion: "Cotizaciones de exportación",
        icono: "pi-dollar",
        color: "#8E44AD",
        tablas: [
          { id: "incoterm", titulo: "Incoterms", icono: "pi-globe" },
          { id: "docRequeridaVentas", titulo: "Documentos Requeridos Ventas", icono: "pi-file-check" },
          { id: "requisitoDocPorPais", titulo: "Requisitos Doc. por País", icono: "pi-flag" },
          { id: "tipoContenedor", titulo: "Tipo Contenedor", icono: "pi-box" },
          { id: "formaTransaccion", titulo: "Formas Transacción", icono: "pi-credit-card" },
        ],
      },
      {
        id: "preFactura",
        titulo: "Pre-Facturas",
        descripcion: "Pre-facturas de exportación",
        icono: "pi-file",
        color: "#5DADE2",
        tablas: [
          { id: "moneda", titulo: "Monedas", icono: "pi-money-bill" },
          { id: "tipoEntidad", titulo: "Tipos Entidad", icono: "pi-briefcase" },
          { id: "agrupacionEntidad", titulo: "Agrupaciones Entidad", icono: "pi-sitemap" },
          { id: "unidadMedida", titulo: "Unidad Medida", icono: "pi-chart-bar" },
          { id: "personal", titulo: "Personal", icono: "pi-users" },
          { id: "cargoPersonal", titulo: "Cargos Personal", icono: "pi-id-card" },
          { id: "pais", titulo: "País", icono: "pi-flag" },
          { id: "familiaProducto", titulo: "Familia Producto", icono: "pi-th-large" },
          { id: "subfamiliaProducto", titulo: "Subfamilia Producto", icono: "pi-list" },
        ],
      },
    ],
  },
  4: {
    nombre: "CONGELADOS HIDROBIOLÓGICOS",
    icono: "❄️",
    color: "#0891B2",
    descripcion: "Procesamiento y almacenamiento de productos congelados",
    procesosPrincipales: [
      {
        id: "requerimientoCompra",
        titulo: "Requerimientos de Compra",
        descripcion: "Solicitudes de compra",
        icono: "pi-file-edit",
        color: "#1E8449",
        tablas: [
          { id: "producto", titulo: "Producto", icono: "pi-box" },
          { id: "entidadComercial", titulo: "Entidades Comerciales", icono: "pi-building" },
        ],
      },
      {
        id: "ordenCompra",
        titulo: "Órdenes de Compra",
        descripcion: "Órdenes aprobadas",
        icono: "pi-shopping-cart",
        color: "#1E8449",
        tablas: [
          { id: "formaPago", titulo: "Forma de Pago", icono: "pi-credit-card" },
          { id: "tipoProducto", titulo: "Tipo Producto", icono: "pi-tag" },
          { id: "tipoEstadoProducto", titulo: "Tipo Estado Producto", icono: "pi-circle" },
          { id: "destinoProducto", titulo: "Destino Producto", icono: "pi-map-marker" },
          { id: "modoDespachoRecepcion", titulo: "Modo Despacho/Recepción", icono: "pi-truck" },
        ],
      },
      {
        id: "movimientoAlmacen",
        titulo: "Movimientos de Almacén",
        descripcion: "Control de inventarios",
        icono: "pi-box",
        color: "#2874A6",
        tablas: [
          { id: "conceptoMovAlmacen", titulo: "Conceptos Movimientos", icono: "pi-tags" },
          { id: "tipoDocumento", titulo: "Tipos de Documento", icono: "pi-file" },
          { id: "tipoConcepto", titulo: "Tipos de Concepto", icono: "pi-tag" },
          { id: "tipoMovimientoAlmacen", titulo: "Tipos de Movimiento", icono: "pi-arrows-h" },
          { id: "tipoAlmacen", titulo: "Tipos de Almacén", icono: "pi-building" },
          { id: "centrosAlmacen", titulo: "Centros de Almacén", icono: "pi-sitemap" },
          { id: "almacen", titulo: "Almacenes", icono: "pi-warehouse" },
          { id: "serieDoc", titulo: "Series de Documento", icono: "pi-hashtag" },
        ],
      },
      {
        id: "cotizacionVentas",
        titulo: "Cotización Ventas",
        descripcion: "Cotizaciones de exportación",
        icono: "pi-dollar",
        color: "#8E44AD",
        tablas: [
          { id: "incoterm", titulo: "Incoterms", icono: "pi-globe" },
          { id: "docRequeridaVentas", titulo: "Documentos Requeridos Ventas", icono: "pi-file-check" },
          { id: "requisitoDocPorPais", titulo: "Requisitos Doc. por País", icono: "pi-flag" },
          { id: "tipoContenedor", titulo: "Tipo Contenedor", icono: "pi-box" },
          { id: "formaTransaccion", titulo: "Formas Transacción", icono: "pi-credit-card" },
        ],
      },
      {
        id: "preFactura",
        titulo: "Pre-Facturas",
        descripcion: "Pre-facturas de exportación",
        icono: "pi-file",
        color: "#5DADE2",
        tablas: [
          { id: "moneda", titulo: "Monedas", icono: "pi-money-bill" },
          { id: "tipoEntidad", titulo: "Tipos Entidad", icono: "pi-briefcase" },
          { id: "agrupacionEntidad", titulo: "Agrupaciones Entidad", icono: "pi-sitemap" },
          { id: "personal", titulo: "Personal", icono: "pi-users" },
          { id: "cargoPersonal", titulo: "Cargos Personal", icono: "pi-id-card" },
          { id: "pais", titulo: "País", icono: "pi-flag" },
          { id: "familiaProducto", titulo: "Familia Producto", icono: "pi-th-large" },
          { id: "subfamiliaProducto", titulo: "Subfamilia Producto", icono: "pi-list" },
          { id: "unidadMedida", titulo: "Unidad Medida", icono: "pi-chart-bar" },
        ],
      },
    ],
  },
  5: {
    nombre: "AGROINDUSTRIAS",
    icono: "🌾",
    color: "#65A30D",
    descripcion: "Producción y comercialización de productos agroindustriales",
    procesosPrincipales: [
      {
        id: "requerimientoCompra",
        titulo: "Requerimientos de Compra",
        descripcion: "Solicitudes de compra",
        icono: "pi-file-edit",
        color: "#1E8449",
        tablas: [
          { id: "producto", titulo: "Producto", icono: "pi-box" },
          { id: "entidadComercial", titulo: "Entidades Comerciales", icono: "pi-building" },
        ],
      },
      {
        id: "ordenCompra",
        titulo: "Órdenes de Compra",
        descripcion: "Órdenes aprobadas",
        icono: "pi-shopping-cart",
        color: "#1E8449",
        tablas: [
          { id: "formaPago", titulo: "Forma de Pago", icono: "pi-credit-card" },
          { id: "tipoProducto", titulo: "Tipo Producto", icono: "pi-tag" },
          { id: "tipoEstadoProducto", titulo: "Tipo Estado Producto", icono: "pi-circle" },
          { id: "destinoProducto", titulo: "Destino Producto", icono: "pi-map-marker" },
          { id: "modoDespachoRecepcion", titulo: "Modo Despacho/Recepción", icono: "pi-truck" },
        ],
      },
      {
        id: "movimientoAlmacen",
        titulo: "Movimientos de Almacén",
        descripcion: "Control de inventarios",
        icono: "pi-box",
        color: "#2874A6",
        tablas: [
          { id: "conceptoMovAlmacen", titulo: "Conceptos Movimientos", icono: "pi-tags" },
          { id: "tipoDocumento", titulo: "Tipos de Documento", icono: "pi-file" },
          { id: "tipoConcepto", titulo: "Tipos de Concepto", icono: "pi-tag" },
          { id: "tipoMovimientoAlmacen", titulo: "Tipos de Movimiento", icono: "pi-arrows-h" },
          { id: "tipoAlmacen", titulo: "Tipos de Almacén", icono: "pi-building" },
          { id: "centrosAlmacen", titulo: "Centros de Almacén", icono: "pi-sitemap" },
          { id: "almacen", titulo: "Almacenes", icono: "pi-warehouse" },
          { id: "serieDoc", titulo: "Series de Documento", icono: "pi-hashtag" },
        ],
      },
      {
        id: "cotizacionVentas",
        titulo: "Cotización Ventas",
        descripcion: "Cotizaciones de exportación",
        icono: "pi-dollar",
        color: "#8E44AD",
        tablas: [
          { id: "incoterm", titulo: "Incoterms", icono: "pi-globe" },
          { id: "docRequeridaVentas", titulo: "Documentos Requeridos Ventas", icono: "pi-file-check" },
          { id: "requisitoDocPorPais", titulo: "Requisitos Doc. por País", icono: "pi-flag" },
          { id: "tipoContenedor", titulo: "Tipo Contenedor", icono: "pi-box" },
          { id: "formaTransaccion", titulo: "Formas Transacción", icono: "pi-credit-card" },
        ],
      },
      {
        id: "preFactura",
        titulo: "Pre-Facturas",
        descripcion: "Pre-facturas de exportación",
        icono: "pi-file",
        color: "#5DADE2",
        tablas: [
          { id: "moneda", titulo: "Monedas", icono: "pi-money-bill" },
          { id: "tipoEntidad", titulo: "Tipos Entidad", icono: "pi-briefcase" },
          { id: "agrupacionEntidad", titulo: "Agrupaciones Entidad", icono: "pi-sitemap" },
          { id: "unidadMedida", titulo: "Unidad Medida", icono: "pi-chart-bar" },
          { id: "personal", titulo: "Personal", icono: "pi-users" },
          { id: "cargoPersonal", titulo: "Cargos Personal", icono: "pi-id-card" },
          { id: "pais", titulo: "País", icono: "pi-flag" },
          { id: "tipoContrato", titulo: "Tipo Contrato", icono: "pi-file-edit" },
          { id: "familiaProducto", titulo: "Familia Producto", icono: "pi-th-large" },
          { id: "subfamiliaProducto", titulo: "Subfamilia Producto", icono: "pi-list" },
        ],
      },
    ],
  },
  6: {
    nombre: "SERVICIOS",
    icono: "🏭",
    color: "#7C3AED",
    descripcion: "Servicios de almacenamiento y logística para terceros",
    procesosPrincipales: [
      {
        id: "contratoServicio",
        titulo: "Contratos de Servicios",
        descripcion: "Gestión de contratos",
        icono: "pi-file-check",
        color: "#E67E22",
        tablas: [
          { id: "producto", titulo: "Producto", icono: "pi-box" },
          { id: "entidadComercial", titulo: "Entidades Comerciales", icono: "pi-building" },
          { id: "tipoContrato", titulo: "Tipo Contrato", icono: "pi-file-edit" },
        ],
      },
      {
        id: "preFactura",
        titulo: "Pre-Facturas",
        descripcion: "Pre-facturas de servicios",
        icono: "pi-file",
        color: "#5DADE2",
        tablas: [
          { id: "moneda", titulo: "Monedas", icono: "pi-money-bill" },
          { id: "tipoEntidad", titulo: "Tipos Entidad", icono: "pi-briefcase" },
          { id: "agrupacionEntidad", titulo: "Agrupaciones Entidad", icono: "pi-sitemap" },
          { id: "personal", titulo: "Personal", icono: "pi-users" },
          { id: "cargoPersonal", titulo: "Cargos Personal", icono: "pi-id-card" },
          { id: "pais", titulo: "País", icono: "pi-flag" },
          { id: "tipoContrato", titulo: "Tipo Contrato", icono: "pi-file-edit" },
          { id: "familiaProducto", titulo: "Familia Producto", icono: "pi-th-large" },
          { id: "subfamiliaProducto", titulo: "Subfamilia Producto", icono: "pi-list" },
          { id: "unidadMedida", titulo: "Unidad Medida", icono: "pi-chart-bar" },
        ],
      },
      {
        id: "movimientoAlmacen",
        titulo: "Movimientos de Almacén",
        descripcion: "Control de inventarios",
        icono: "pi-box",
        color: "#2874A6",
        tablas: [
          { id: "conceptoMovAlmacen", titulo: "Conceptos Movimientos", icono: "pi-tags" },
          { id: "tipoDocumento", titulo: "Tipos de Documento", icono: "pi-file" },
          { id: "tipoConcepto", titulo: "Tipos de Concepto", icono: "pi-tag" },
          { id: "tipoMovimientoAlmacen", titulo: "Tipos de Movimiento", icono: "pi-arrows-h" },
          { id: "tipoAlmacen", titulo: "Tipos de Almacén", icono: "pi-building" },
          { id: "centrosAlmacen", titulo: "Centros de Almacén", icono: "pi-sitemap" },
          { id: "almacen", titulo: "Almacenes", icono: "pi-warehouse" },
          { id: "serieDoc", titulo: "Series de Documento", icono: "pi-hashtag" },
        ],
      },
      {
        id: "oTMantenimiento",
        titulo: "Órdenes de Trabajo",
        descripcion: "Mantenimiento",
        icono: "pi-wrench",
        color: "#DC2626",
        tablas: [
          { id: "activo", titulo: "Activos", icono: "pi-cog" },
          { id: "tipoActivo", titulo: "Tipos de Activo", icono: "pi-tag" },
          { id: "tipoMantenimiento", titulo: "Tipos de Mantenimiento", icono: "pi-wrench" },
        ],
      },
      {
        id: "requerimientoCompra",
        titulo: "Requerimientos de Compra",
        descripcion: "Solicitudes de compra",
        icono: "pi-file-edit",
        color: "#1E8449",
        tablas: [
          { id: "tipoProducto", titulo: "Tipo Producto", icono: "pi-tag" },
          { id: "tipoEstadoProducto", titulo: "Tipo Estado Producto", icono: "pi-circle" },
          { id: "destinoProducto", titulo: "Destino Producto", icono: "pi-map-marker" },
          { id: "modoDespachoRecepcion", titulo: "Modo Despacho/Recepción", icono: "pi-truck" },
        ],
      },
      {
        id: "ordenCompra",
        titulo: "Órdenes de Compra",
        descripcion: "Órdenes aprobadas",
        icono: "pi-shopping-cart",
        color: "#1E8449",
        tablas: [
          { id: "formaPago", titulo: "Forma de Pago", icono: "pi-credit-card" },
        ],
      },
    ],
  },
};

/**
 * LISTA DE UNIDADES (para selector)
 * Usada por: DashboardUnidades.jsx
 */
export const unidadesNegocio = [
  {
    id: 1,
    nombre: "PESCA INDUSTRIAL",
    icono: "🚢",
    color: "#1E40AF",
    descripcion: "Temporadas, faenas, descargas y cuotas de pesca industrial",
  },
  {
    id: 2,
    nombre: "PESCA CONSUMO",
    icono: "🐟",
    color: "#059669",
    descripcion: "Novedades, faenas y descargas de pesca de consumo humano",
  },
  {
    id: 3,
    nombre: "CONSERVAS DE PESCADO",
    icono: "🥫",
    color: "#DC2626",
    descripcion: "Producción y comercialización de conservas hidrobiológicas",
  },
  {
    id: 4,
    nombre: "CONGELADOS HIDROBIOLÓGICOS",
    icono: "❄️",
    color: "#0891B2",
    descripcion: "Procesamiento y almacenamiento de productos congelados",
  },
  {
    id: 5,
    nombre: "AGROINDUSTRIAS",
    icono: "🌾",
    color: "#65A30D",
    descripcion: "Producción y comercialización de productos agroindustriales",
  },
  {
    id: 6,
    nombre: "SERVICIOS DE ALMACENES",
    icono: "🏭",
    color: "#7C3AED",
    descripcion: "Servicios de almacenamiento y logística para terceros",
  },
];

/**
 * Función auxiliar: Calcular total de módulos por unidad
 */
export const calcularModulosPorUnidad = (unidadId) => {
  const unidad = modulosPorUnidad[unidadId];
  if (!unidad) return 0;
  
  const totalProcesos = unidad.procesosPrincipales?.length || 0;
  const totalTablas = unidad.procesosPrincipales?.reduce(
    (acc, proceso) => acc + (proceso.tablas?.length || 0),
    0
  ) || 0;
  
  return totalProcesos + totalTablas;
};
